project:
  type: website
  output-dir: docs

website:
  title: "Carlos Cardona Andrade"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - projects.qmd
      - href: cv/carlos_cardona_cv.pdf
        text: Resume

format:
  html:
    theme: 
        - sandstone
        - html/custom.scss
    toc: false
    highlight-style: monokai

editor: visual

