project:
  type: website
  output-dir: docs

website:
  title: "Carlos Cardona Andrade"
  search: false
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - projects.qmd
      - href: cv/carlos_cardona_cv.pdf
        text: Resume

format:
  html:
    theme: 
        dark: slate
        light: flatly
    css: styles.css
    toc: true

editor: visual

