project:
  type: website
  output-dir: docs

website:
  title: "Carlos Cardona Andrade"
  search: false
  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - projects.qmd
      - href: cv/carlos_cardona_cv.pdf
        target: _blank
        text: Resume
    background: "#F8F5F0"
  page-footer: 
    left: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/){target="_blank"}</span>
    right: |  
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub](https://github.com/ccardonaandrade/ccardonaandrade.github.io){target="_blank"}</span>
    background: "#F8F5F0"
format:
  html:
    theme: 
        - sandstone
        - html/style.css
    fontawesome: true
    toc: false
    highlight-style: monokai
editor: visual

