project:
  type: website
  output-dir: docs

website:
  title: "Carlos Cardona Andrade"
  search: false
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - teaching.qmd
      - projects.qmd
      - href: cv/carlos_cardona_cv.pdf
        target: _blank
        text: Resume
  page-footer: 
    right: |
     <span class="faux-block">Made with <i class="fab fa-r-project"></i> and <a href="https://quarto.org/">Quarto</a></span>
     <span class="faux-block"><a href="https://github.com/ccardonaandrade/ccardonaandrade.github.io"><i class="fab fa-github"></i> View the source at GitHub</a></span>

format:
  html:
    theme: 
        - sandstone
        - html/custom.scss
    fontawesome: true
    toc: false
    highlight-style: monokai

editor: visual

