---
title: "Teaching"
subtitle: "Syllabi and websites for some of the courses I have taught in the UK and Colombia"
---

Please find my teaching statement [here](teaching_statement/teaching_statement.pdf){target="_blank"}

## Undergraduate

### Lecturer at Universidad Javeriana

-   Data Analysis in R

    -   You can find [here](https://github.com/ccardonaandrade/analisis_de_datos/tree/main){target="_blank"} all the material, including syllabus and slides in Spanish.

### Graduate Teaching Assistant at University of Warwick

-   [EC124: Statistical Techniques](https://warwick.ac.uk/fac/soc/economics/current/modules/ec124/){target="_blank"}

-   [EC203: Applied Econometrics](https://warwick.ac.uk/fac/soc/economics/current/modules/ec203/){target="_blank"} - [Teaching Evaluation](teach_eval/ec203_carlos_cardona.pdf){target="_blank"}

-   [EC108: Industrial Economics 1: Market Structure](https://warwick.ac.uk/fac/soc/economics/current/modules/ec208/){target="_blank"} - [Teaching Evaluation 1](teach_eval/ec208_I_carlos_cardona.pdf){target="_blank"}, [2](teach_eval/ec208_II_carlos_cardona.pdf){target="_blank"}

-   [EC226: Econometrics I](https://warwick.ac.uk/fac/soc/economics/current/modules/ec226/) - [Teaching Evaluation](teach_eval/ec226_carlos_cardona.pdf){target="_blank"}

-   [EC131: Economics for Business](https://warwick.ac.uk/fac/soc/economics/current/modules/ec131/){target="_blank"}

### Lecturer at Universidad del Rosario

-   Quantitative Analysis I

    -   You can find here the [syllabus](https://github.com/ccardonaandrade/analisis_cuantitativo/blob/main/syllabus.pdf){target="_blank"} and the [slides](https://github.com/ccardonaandrade/analisis_cuantitativo/tree/main/slides){target="_blank"}. All the material is in Spanish.

### Teaching Assistant at Universidad del Rosario

-   Microeconomics II

-   Principles of Microeconomics

-   Integral Calculus

-   Principles of Economics

### Teaching Assistant at CESA

-   Microeconomics
